### ISSUE TITLE
missing wiki docs

### ISSUE THREAD

**Issue by endofline** [nylonee/hangupsbot#151]
Some plugins/components have incomplete or missing documentation in the wiki:
* [X] conv_tools (https://github.com/nylonee/hangupsbot/wiki/Conversation-Tools-Plugin)
* [X] image_memegenerator (https://github.com/nylonee/hangupsbot/wiki/Image-Linker:-Meme-Generator-Plugin)
* [X] image_links (added to list in https://github.com/nylonee/hangupsbot/wiki/Plugin-List)
* [x] monitoradds (https://github.com/nylonee/hangupsbot/wiki/Monitoradds-Plugin)
* [X] cleverbot (https://github.com/nylonee/hangupsbot/wiki/Cleverbot-Plugin)
* [x] image_screenshot (https://github.com/nylonee/hangupsbot/wiki/Image-Screenshot-Plugin)
* [X] image_linker_reddit (https://github.com/nylonee/hangupsbot/wiki/Image-Linker:-Reddit-Plugin)
* [x] broadcast command (re: #139) in default plugin (https://github.com/nylonee/hangupsbot/wiki/Default-Commands-Plugin#admin-only-commands)
* [X] updated sink development (https://github.com/nylonee/hangupsbot/wiki/Sinks-(2.4-and-above), re: #123, #153)
* [x] convtools_invitations (re: #114)

*Update the above list or submit a comment to request additional docs*

**Comment by Riptides** [comment]
not on your list but I'll write one for monitoradds in the near future

**Comment by endofline** [comment]
thanks @Riptides - added the item, let @nylonee know if you don't have wiki access already

**Comment by Riptides** [comment]
added https://github.com/nylonee/hangupsbot/wiki/Monitoradds-Plugin
will work on some of the others after work

**Comment by endofline** [comment]
@Riptides - I added a few example snippets to the wiki page, have a look at it and see whether it's right

**Comment by endofline** [comment]
renamed `screenshot` plugin to `image_screenshot` to keep consistency of image-based plugin names

**Comment by Riptides** [comment]
@endofline looks good

**Comment by Riptides** [comment]
@endofline added a wiki page for the screenshot plugin. The installation instructions for PhantomJS I admittedly haven't tested (just copy/pasted from their homepage) because I installed it via a node.js wrapper. I'll spin up a fresh VM tonight and make sure there are no issues.

**Comment by endofline** [comment]
thanks @Riptides - re-formatted the wiki a bit :)

**Comment by nylonee** [comment]
Finished off the others on this list and synced the plugins list with the current staging branch.
